package ui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import model.BotschutzClickListener;
import model.BotschutzInterface;
import model.BotschutzParams;
import util.Log;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JLabel;


/**
 *
 * @author Nico
 */
public class BotschutzPanel extends javax.swing.JPanel implements MouseListener, BotschutzInterface {

    private BotschutzClickListener listener;
    private BotschutzParams unsolvedParams;
    private JLabel label;
    private JDialog dialog;

    /**
     * Creates new form BotschutzPanel
     *
     * @param dialog
     */
    public BotschutzPanel() {
        initComponents();
        addMouseListener(this);
    }

    @Override
    public void showBotschutzImage(String sid, String captchaId, BotschutzClickListener listener) {
        try {
            this.listener = listener;
            this.unsolvedParams = new BotschutzParams(sid, captchaId);
            this.unsolvedParams.image = ImageIO.read(new URL("http://engine10.earthlost.de/captcha.php?id=" + captchaId + "&sid=" + sid));
            this.label = new JLabel();
            repaint();
            //JOptionPane.showConfirmDialog(null, this, "JOptionPane Example : ", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

//            JOptionPane jop = new JOptionPane();
//            jop.setMessage(this);
//            dialog = jop.createDialog(unsolvedParams.title);
//            dialog.setVisible(true);
            dialog = new JDialog();
            dialog.setModal(true);
            dialog.setContentPane(this);
            dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
            dialog.pack();
            dialog.setVisible(true);

        } catch (IOException ex) {
            Log.err(ex);
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (unsolvedParams != null && unsolvedParams.image != null) {
            g.drawImage(unsolvedParams.image, 0, 0, this); // see javadoc for more info on the parameters  
        } else {
            g.setColor(new Color(219, 222, 227));
            g.fillRect(0, 0, 460, 118);
        }
    }

    @Override
    public void mouseClicked(MouseEvent e) {
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        dialog.dispose();
        if (listener != null) {
            unsolvedParams.x = e.getX();
            unsolvedParams.y = e.getY();
            listener.onBotschutzClicked(unsolvedParams);
        }
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(460, 118));
        setMinimumSize(new java.awt.Dimension(460, 118));
        setPreferredSize(new java.awt.Dimension(460, 118));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
