/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import interfaces.LoginListener;
import util.ClipboardListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author nico
 */
public class LoginPanel extends javax.swing.JPanel implements ClipboardListener.EntryListener {

    private final LoginListener loginListener;

    /**
     * Creates new form LoginPanel
     *
     * @param loginListener
     */
    public LoginPanel(LoginListener loginListener) {
        initComponents();
        this.loginListener = loginListener;
        setLoginButtonVisibility();
        ClipboardListener listener = new ClipboardListener();
        listener.setEntryListener(this);
        listener.start();
        edt_sid.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setLoginButtonVisibility();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setLoginButtonVisibility();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setLoginButtonVisibility();
            }
        });

    }

    private void setLoginButtonVisibility() {
        String sidRegex = "([a-z0-9]{26})";
        Matcher matcher = Pattern.compile(sidRegex).matcher(edt_sid.getText());
        jButton1.setVisible(matcher.matches());
    }

    @Override
    public void onCopy(String data) {

        String sidRegex = "http(?:s)?:\\/\\/www\\.earthlost\\.de\\/(?:play|main)\\.phtml\\?sid=([a-z0-9]{26})";
        Matcher matcher = Pattern.compile(sidRegex).matcher(data);
        if (matcher.matches()) {
            edt_sid.setText(matcher.group(1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edt_sid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("<html>Zum anmelden wird die sid aus der Adressleiste deines Browsers gebraucht. <br>\nDu kannst auch die ganze URL kopieren. Zb:<br>  http://www.earthlost.de/play.phtml?sid=rm80o7djblciv3jjf923u4sie4");

        jButton1.setText("Tool starten");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edt_sid, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edt_sid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(205, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginListener.onLogin(edt_sid.getText());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edt_sid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
