/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import interfaces.LoginListener;
import model.BotschutzClickListener;
import model.BotschutzInterface;
import model.IntroPage;
import network.NetworkRequest;
import java.util.prefs.Preferences;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

/**
 *
 * @author nico
 */
public class MainFrame extends javax.swing.JFrame implements LoginListener, BotschutzInterface {

    private final BotschutzPanel botschutzPanel;
    private LoginPanel loginPanel;
    private MainPanel mainPanel;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        botschutzPanel = new BotschutzPanel();
        NetworkRequest.getNetwork().init(botschutzPanel);
        loginPanel = new LoginPanel(this);

        Preferences prefs = Preferences.userNodeForPackage(this.getClass());
        String sid = prefs.get("sid", "");
        getContentPane().add(loginPanel);
        if (sid.equals("")) {
            pack();
            revalidate();
        } else {
            onLogin(sid);
        }
    }

    @Override
    public void showBotschutzImage(String sid, String captchaId, BotschutzClickListener listener) {

    }

    @Override
    public void onLogin(String sid) {
        NetworkRequest.getNetwork().getAPI().intro(sid, null, null, null, null, null, null, null).enqueue(new Callback<IntroPage>() {
            @Override
            public void onResponse(Call<IntroPage> call, Response<IntroPage> rspns) {
                IntroPage intro = rspns.body();
                if (intro != null && !intro.sid.equals("")) {
                    Preferences prefs = Preferences.userNodeForPackage(this.getClass());
                    prefs.put("sid", sid);
                    getContentPane().remove(loginPanel);
                    mainPanel = new MainPanel(sid, MainFrame.this);
                    getContentPane().add(mainPanel);
                    pack();
                    revalidate();
                }
            }

            @Override
            public void onFailure(Call<IntroPage> call, Throwable thrwbl) {

            }
        });

    }

    @Override
    public void onLogout() {
        Preferences prefs = Preferences.userNodeForPackage(this.getClass());
        prefs.put("sid", "");
        getContentPane().remove(mainPanel);
        getContentPane().add(loginPanel);
        pack();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
